name: build-image

on:
  push:
    branches:
      - "main"

jobs:
  buildImage:
    strategy:
      matrix:
        platformName:
          - ARM64
          - AMD64

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: wget
        uses: wei/wget@v1
        with:
          args: -O SentimentAnalysisKOBert.pt ${{ secrets.modelURL }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@15c905b16b06416d2086efa066dd8e3a35cc7f98
        with:
          driver-opts: "image=moby/buildkit:v0.10.5"
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCRTOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ matrix.platformName }}.Dockerfile
          platforms: linux/${{ matrix.platformName }}
          push: true
          tags: ghcr.io/aglide100/kobert-based-simple-korean-semantic-analyzer:latest
